{
 "title": "MySQL Dashboard",
 "description": "The Dashboard display Visualization Data from MySQL Exporter configured with Prometheus Database",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,10m,30m,1h,6h,12h" },
   {
    "name": "host",
    "label": "Server",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall Status ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Query/Sec",
   "type": "gauge",
   "description": "Queries Processed By Server Per Second\n",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=\"$host\"}[$interval]) "
    }
   ]
  },
  {
   "title": "Scrape Count",
   "type": "stat",
   "description": "Number of data scrapes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_exporter_scrapes_total" }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "stat",
   "description": "InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  ",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size"
    }
   ]
  },
  {
   "title": "Connection Attempts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_connections"
    }
   ]
  },
  {
   "title": "MySQL Uptime",
   "type": "stat",
   "description": "The time elapsed since the last restart of the MySQL server.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "description": "Display Maximum Connections",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Active Connections"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Thread Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Connected Threads"
    },
    {
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "Maximum Connections"
    },
    {
     "expr": "mysql_global_status_threads_running",
     "legendFormat": "Running Threads"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_connection_errors_total{instance=~\"$host\"}[$interval])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "Tables , Queries and Questions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_opened_tables",
     "legendFormat": "Opened Tables"
    },
    {
     "expr": "mysql_global_status_open_tables",
     "legendFormat": "Open Tables"
    }
   ]
  },
  {
   "title": "MySQL Questions and Query Rates",
   "type": "graph",
   "description": "Query and Question counts",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{instance=~\"$host\"}[5m])",
     "legendFormat": "Questions"
    },
    {
     "expr": "rate(mysql_global_status_queries[5m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Processes, Commands and Handlers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Top Command Counters Hourly",
   "type": "graph",
   "description": "Top Command Counters Hourly",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, increase(mysql_global_status_commands_total{instance=~\"$host\"}[1h])>0)",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "graph",
   "description": "Handler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval])\r",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "MySQL Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "description": "Network traffic generated by MySQL",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=\"$host\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=\"$host\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "MySQL Network Usage Hourly",
   "type": "graph",
   "description": "Network traffic generated by MySQL per hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(mysql_global_status_bytes_received{instance=\"$host\"}[1h])",
     "legendFormat": "Received"
    },
    {
     "expr": "increase(mysql_global_status_bytes_sent{instance=\"$host\"}[1h])",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Memory and Cache Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "graph",
   "description": "\nInnoDB Buffer Pool Data- InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n\nKey Buffer Size- Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n\nInnoDB Log Buffer Size-The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_page_size{instance=\"$host\"} * on (instance) mysql_global_status_buffer_pool_pages{instance=\"$host\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=\"$host\"}",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"}",
     "legendFormat": "Key Buffer Size"
    }
   ]
  },
  {
   "title": "MySQL Open Tables",
   "type": "graph",
   "description": "\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\n",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_tables{instance=~\"$host\"}",
     "legendFormat": "Open Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache{instance=~\"$host\"}",
     "legendFormat": "Table Open Cache"
    }
   ]
  },
  {
   "title": "MySQL Thread Cache",
   "type": "graph",
   "description": "\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. \n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_thread_cache_size{instance=~\"$host\"}",
     "legendFormat": "Thread Cache Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_cached{instance=~\"$host\"}",
     "legendFormat": "Threads Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_threads_created{instance=~\"$host\"}[$interval])",
     "legendFormat": "Threads Created"
    }
   ]
  },
  {
   "title": "MySQL Table Definition Cache",
   "type": "graph",
   "description": "\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_table_definitions{instance=~\"$host\"}",
     "legendFormat": "Open Table Definitions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache{instance=~\"$host\"}",
     "legendFormat": "Table Definitions Cache Size"
    }
   ]
  }
 ]
}